url: https://www.ilgattarossa.org
lang: it
locale: "it-IT"
description: "IlGattarossa è (stato) il folle tentativo di un gruppo di artisti di portare la propria Opera al pubblico senza mediazioni"
images: /assets/images
og-image: /assets/images/igr_og.png
og-image-width: 1200
og-image-height: 630
# default paths for images
featured:       /assets/images/featured
galleries:      /assets/images/galleries
responsive:     /assets/images/responsive
# sizes for responsive images
srcset:         
    - 380
    - 640
    - 960
    - 1280
    - 1600

defaults:    
  - scope:
      path: ""
    values:
      author: "1G°R"
  - scope:
      path: ""
      type: "pages"
    values:
      title: "ilgattarossa.org"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      description: 
  - scope:
      path: "_posts/eventi"
      type: "posts"  
    values:
      category: "Eventi"
      layout: event
      permalink: /eventi/:slug
  - scope:
      path: "_posts/foto"
      type: "posts"  
    values:
      category: "Foto"
      subtitle: "Galleria Fotografica"
      credits: "Foto di Alberto Gori"
      permalink: /foto/:slug      
  - scope:
      path: "_posts/video"
      type: "posts"  
    values:
      category: "Video"
      subtitle: "Documentazione dell'Evento"
      permalink: /video/:slug
  - scope:
      path: ""
    values:
      layout: "default"
    
