backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow  
media_folder: 'assets/images/uploads'
collections:
  - name: 'eventi'
    label: 'Eventi'
    folder: '_posts/eventi'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "event"}
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Sottotitolo", name: "subtitle", widget: "string"}
      - {label: "Crediti", name: "credits", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
